version: "3.7"
services:
  front-envoy:
    container_name: emulator_envoy
    networks:
      - envoymesh
    expose:
      - "8080"
      - "8001"
      - "8443"
    ports:
      - "80:8080"
      - "8001:8001"

  emulator:
    container_name: emulator_emulator
    networks:
      envoymesh:
        aliases:
          - emulator
    devices: [/dev/kvm]
    shm_size: 128M
    expose:
      - "8554"
      - "5555"
      - "5554"
   # secrets:
   #   - adbkey

  jwt_signer:
    container_name: emulator_jwt_signer
    networks:
      envoymesh:
        aliases:
          - jwt_signer
    expose:
      - "8080"

  nginx:
    container_name: emulator_nginx
    networks:
      envoymesh:
        aliases:
          - nginx
    expose:
      - "80"

  emulator_controller:
    container_name: emulator_emulator_controller
    networks:
      envoymesh:
        aliases:
          - emulator_controller
    expose:
      - "80"
    environment:
      - PORT=80 # This currently gets overwritten (see explaination in emulator-controller/webpack.config.js)

networks:
  envoymesh: {}

#secrets:
#  adbkey:
#    file: ~/.android/adbkey
