version: "3.7"
services:
  front-envoy:
    image: acremuglobal.azurecr.io/emulator_envoy:dev
    ports:
      - "443:8443"
    restart: unless-stopped

  emulator:
    image: acremuglobal.azurecr.io/emulator_emulator:dev
    restart: unless-stopped

  jwt_signer:
    image: acremuglobal.azurecr.io/emulator_jwt_signer:dev
    restart: unless-stopped

  nginx:
    image: acremuglobal.azurecr.io/emulator_nginx:dev
    restart: unless-stopped

  emulator_controller:
    image: acremuglobal.azurecr.io/emulator_emulator_controller:dev
    restart: unless-stopped
