version: "3.7"
services:
  front-envoy:
    image: acremuglobal.azurecr.io/emulator_envoy:gpu-test
    ports:
      - "443:8443"
    restart: unless-stopped

  emulator:
    image: acremuglobal.azurecr.io/emulator_emulator:gpu-test
    restart: unless-stopped

  jwt_signer:
    image: acremuglobal.azurecr.io/emulator_jwt_signer:gpu-test
    restart: unless-stopped

  nginx:
    image: acremuglobal.azurecr.io/emulator_nginx:gpu-test
    restart: unless-stopped

  emulator_controller:
    image: acremuglobal.azurecr.io/emulator_emulator_controller:gpu-test
    restart: unless-stopped
