version: "3.7"
services:
  front-envoy:
    image: acremuglobal.azurecr.io/emulatorstack_envoy:1.0
    networks:
      - envoymesh
    expose:
      - "8080"
      - "8001"
      - "8443"
    ports:
      - "80:8080"
      - "8001:8001"
      - "443:8443"
    restart: unless-stopped

  emulator:
    image: acremuglobal.azurecr.io/emulatorstack_emulator:7190274_2020-12-17.zip
    networks:
      envoymesh:
        aliases:
          - emulator
    shm_size: 128M
    expose:
      - "8554"
      - "5555"
      - "5554"
    devices:
      - "/dev/kvm"
    secrets:
      - adbkey
    environment:
      - TURN
    restart: unless-stopped
    # logging:
    #   driver: "none"

  nginx:
    image: acremuglobal.azurecr.io/emulatorstack_nginx:1.0
    networks:
      envoymesh:
        aliases:
          - nginx
    expose:
      - "80"
    restart: unless-stopped

  emulator_controller:
    image: acremuglobal.azurecr.io/emulatorstack_emulator_controller:1.0
    networks:
      envoymesh:
        aliases:
          - emulator_controller
    expose:
      - "80"
    environment:
      - PORT=80 # This currently gets overwritten (see explaination in emulator-controller/webpack.config.js)
    restart: unless-stopped

networks:
  envoymesh: {}

secrets:
  adbkey:
    file: ~/.android/adbkey
